### ISSUE TITLE
[Add Testcase]  Firefox

### ISSUE THREAD

**Issue by Michaelnlearn** [ArielHeleneto/RISCV-testcase#12]
### 请选择：

- [X] 我已经检查了 [Issue](https://github.com/brsf11/mugen-riscv/issues)，进行了搜索，但没有发现类似问题。
- [X] 我正在着手整理该测试用例库。
- [X] 我希望接手该测试用例库。

### 软件名称

Firefox

### 软件版本

Firefox riscv64 

### 操作系统版本

openEuler 22.03 LTS riscv64

### 软件描述

Firefox是一款流行的浏览器

### 已有测试用例来源

目前已有的测试用例：https://github.com/Michaelnlearn/test/tree/main/Firefox

**Comment by ArielHeleneto** [comment]
#23 Reviewing

**Comment by ArielHeleneto** [comment]
#23 Finished but without pictures.
