### ISSUE TITLE
[Add Testcase] Gimp

### ISSUE THREAD

**Issue by FIFCC** [ArielHeleneto/RISCV-testcase#8]
### 请选择：

- [x] 我已经检查了 [Issue](https://github.com/brsf11/mugen-riscv/issues)，进行了搜索，但没有发现类似问题。
- [x] 我正在着手整理该测试用例库。
- [X] 我希望接手该测试用例库。

### 软件名称

gimp

### 软件版本

gimp-2 riscv64 2.99.6-3.oe2203

### 操作系统版本

openEuler 22.03-v1 riscv64

### 软件描述

GIMP是一个多平台工具，用于创建和编辑各种图像。GIMP是GNU Image Manipulation Program 的首字母缩写。GIMP有很多功能。它可以用作简单的绘画程序、专家级的照片修饰程序、创建数字艺术的工具、在线批处理系统、批量生产的图像渲染器、图像格式转换器等。GIMP是可扩展和可扩展的。它旨在通过插件和扩展来增强以执行任何操作。先进的脚本界面允许从最简单的任务到最复杂的图像处理程序的所有内容都可以轻松编写脚本。

### 已有测试用例来源

目前已有的测试用例：https://gitee.com/yunxiangluo/testsuites/tree/master/GIMP

**Comment by microseyuyu** [comment]
我接手了

**Comment by ArielHeleneto** [comment]
#16 finished
